// <auto-generated />
using System;
using EHBrewingMonitoringDashboard.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EHBrewingMonitoringDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613114609_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EHBrewingMonitoringDashboard.Models.Fermenter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("fermenter", (string)null);
                });

            modelBuilder.Entity("EHBrewingMonitoringDashboard.Models.Measure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("SensorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sensor_id");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("SensorId");

                    b.HasIndex("SensorId", "RecordedAt");

                    b.ToTable("measure", (string)null);
                });

            modelBuilder.Entity("EHBrewingMonitoringDashboard.Models.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<Guid>("FermenterId")
                        .HasColumnType("uuid")
                        .HasColumnName("fermenter_id");

                    b.Property<decimal?>("IdealMaxValue")
                        .HasColumnType("numeric")
                        .HasColumnName("ideal_max_value");

                    b.Property<decimal?>("IdealMinValue")
                        .HasColumnType("numeric")
                        .HasColumnName("ideal_min_value");

                    b.Property<DateTime>("InstalledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("installed_at");

                    b.Property<DateTime?>("LastMaintenanceAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_maintenance_at");

                    b.Property<string>("MeasureUnit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("measure_unit");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("serial_number");

                    b.Property<short>("Type")
                        .HasColumnType("smallint")
                        .HasColumnName("type");

                    b.Property<decimal?>("WarningTolerance")
                        .HasColumnType("numeric")
                        .HasColumnName("warning_tolerance");

                    b.HasKey("Id");

                    b.HasIndex("FermenterId");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("sensor", (string)null);
                });

            modelBuilder.Entity("EHBrewingMonitoringDashboard.Models.Measure", b =>
                {
                    b.HasOne("EHBrewingMonitoringDashboard.Models.Sensor", "Sensor")
                        .WithMany("Measures")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("EHBrewingMonitoringDashboard.Models.Sensor", b =>
                {
                    b.HasOne("EHBrewingMonitoringDashboard.Models.Fermenter", "Fermenter")
                        .WithMany("Sensors")
                        .HasForeignKey("FermenterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fermenter");
                });

            modelBuilder.Entity("EHBrewingMonitoringDashboard.Models.Fermenter", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("EHBrewingMonitoringDashboard.Models.Sensor", b =>
                {
                    b.Navigation("Measures");
                });
#pragma warning restore 612, 618
        }
    }
}
